title: L.Z.Edith / Film Editing Practice # name of the site
author: Elzie Edith # name of site's author
email: l.z.edithor@gmail.com # email of site's author
url: https://lzedith.com # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: A blog about film editing practice, including examples of movie and clip re-edits and informational posts

permalink: /:slug.html

logo: "preview.jpg"
image: "preview.jpg"
favicon: "lzfavicon.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
